apiVersion: apps/v1
kind: Deployment
metadata:
  name: esteban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: thenew
          image: rockstban/volume-kubernetes