apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: esteban-pvc
spec:
  volumeName: esteban-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi