apiVersion: v1
kind: Service
metadata:
  name: pruebas
spec:
  selector:
    app: esteban
  type: LoadBalancer
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gabriel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: esteban
  template:
    metadata:
      labels:
        app: esteban
    spec:
      containers:
        - name: lopez
          image: rockstban/volume-kubernetes:1.2
          env:
           # - name: STORY_FOLDER
            #  value: 'esteban'
            - name: STORY_FOLDER
              valueFrom: 
                configMapKeyRef: 
                  name: esteban-environment
                  key: folder
          volumeMounts:
            - mountPath: /app/esteban
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: esteban-pvc
            
